config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :tvs
  resources :tvshows

end

app/models/tv.rb
class Tv < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :introduction, presence: true, length: { maximum: 160 }
  validates :theme_color, presence: true
  
  has_many :tvshows
end

app/models/tvshow.rb
class Tvshow < ActiveRecord::Base
  belongs_to :tv
  validates :tv_id, presence: true
  validates :introduction, presence: true, length: { maximum: 160 }
  validates :video_url, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tvs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:info] = "ログアウトしました。"
    redirect_to root_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/tvs_controller.rb
class TvsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  before_action :set_user, only: [:edit, :update]
  
  def show
    @tv = Tv.find(params[:id])
    @tvshows = @tv.tvshows.order(created_at: :asc)
    @tvshow = @tv.tvshows.build
    @user = @tv.user
  end

  def create
    @tv = current_user.tvs.build(tv_params)
    if @tv.save
      flash[:success] = "Tv created!"
      redirect_to current_user
    else
      flash[:danger] = "Tv didn't create!"
      render 'users/show'
    end
  end

  def destroy
    @tv = current_user.tvs.find_by(id: params[:id])
    return redirect_to user_url(params[:id]) if @tv.nil?
    @tv.destroy
    flash[:success] = "Tv deleted"
    redirect_to request.referrer || current_user
  end
  
  private
  def tv_params
    params.require(:tv).permit(:title, :introduction, :theme_color)
  end

  def set_user
    @user = User.find(params[:id])
    if @user != current_user
      flash[:danger] = "別のユーザーの編集はできません。"
      redirect_to @user
    end
  end
end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
  include ActionView::Helpers::OutputSafetyHelper
  before_action :logged_in_user, only: [:create]
 #  before_action :set_tv, only: [:create]
  before_action :set_user, only: [:edit, :update, :delete]

  def update
    @tvshow = Tvshow.find(tvshow_params[:front_tvshow_id])
    @tv = @tvshow.tv
    @tvshows = @tv.tvshows
#    @video_url = raw @tvshow.video_url
#    @video_url = raw "<iframe frameborder='0' width='480' height='270' src='//www.dailymotion.com/embed/video/x3w5fk7' allowfullscreen></iframe><br /><a href='http://www.dailymotion.com/video/x3w5fk7_%25E6%25A4%258E%25E5%2590%258D%25E6%259E%2597%25E6%25AA%258E-%25E4%25B8%25B8%25E3%2581%25AE%25E5%2586%2585%25E3%2582%25B5%25E3%2583%2587%25E3%2582%25A3%25E3%2582%25B9%25E3%2583%2586%25E3%2582%25A3%25E3%2583%2583%25E3%2582%25AF_music' target='_blank'>椎名林檎　「丸の内サディスティック」</a> <i>投稿者 <a href='http://www.dailymotion.com/poppo28282828' target='_blank'>poppo2828"
#    @video_url = "<iframe frameborder='0' width='480' height='270' src='//www.dailymotion.com/embed/video/x3w5fk7' allowfullscreen></iframe><br /><a href='http://www.dailymotion.com/video/x3w5fk7_%25E6%25A4%258E%25E5%2590%258D%25E6%259E%2597%25E6%25AA%258E-%25E4%25B8%25B8%25E3%2581%25AE%25E5%2586%2585%25E3%2582%25B5%25E3%2583%2587%25E3%2582%25A3%25E3%2582%25B9%25E3%2583%2586%25E3%2582%25A3%25E3%2583%2583%25E3%2582%25AF_music' target='_blank'>椎名林檎　「丸の内サディスティック」</a> <i>投稿者 <a href='http://www.dailymotion.com/poppo28282828' target='_blank'>poppo28282828</a></i>"
    @video_url = @tvshow.video_url.gsub(/\"/, "'")

     #binding.pry

    #redirect_to @tv
    render 'test'
  end

  def create
    @tv = Tv.find(tvshow_params[:tv_id])
    @tvshow = @tv.tvshows.build(tvshow_params)
    #  flash[:danger] = "【遷移はテキトー】他のユーザーは作成できません。"
    #  render 'tops/index'
    #end
    
    if @tvshow.save
      flash[:success] = "Tvshow created!"
      redirect_to @tv
    else
      flash[:danger] = "Tvshow didn't create!"
      render 'tvs/show'
    end
  end
  

  def destroy
    @tv = Tv.find(tvshow_params[:tv_id])
    @tvshow = @tv.tvshows.find_by(id: params[:id])
    if @tv.nil?
      flash[:success] = "Didn't Tvshow delete"
      return redirect_to @tv
    end
    @tvshow.destroy
    flash[:success] = "Tvshow deleted"
    redirect_to request.referrer || current_user
  end
  
  private
  def tvshow_params
    params.require(:tvshow).permit(:introduction, :video_url, :tv_id, :front_tvshow_id)
  end

#  def set_tv
#    @tv = Tvshow.find(params[:id]).tv
#  end

  def set_user
    @tv = Tvshow.find(tvshow_params[:front_tvshow_id]).tv
    @user = @tv.user
    if @user != current_user
      flash[:danger] = "別のユーザーの編集はできません。"
      redirect_to @user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @tvs = @user.tvs.order(created_at: :desc)
    
    @tv = current_user.tvs.build if logged_in?
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if params[:user][:new_password].blank? || params[:user][:new_password_confirmation].blank?
      if @user.update(user_params)
        # 保存に成功した場合はトップページへリダイレクト
        flash[:success] = 'メッセージを編集しました'
        redirect_to user_path(@user)
      else
        # 保存に失敗した場合は編集画面へ戻す
        flash[:danger] = "失敗１"
        render 'edit'
      end 
    elsif @user && @user.authenticate(params[:user][:password_for_edit]) && params[:user][:new_password]==params[:user][:new_password_confirmation]
      params[:user][:password] = params[:user][:new_password]
      params[:user][:password_confirmation] = params[:user][:new_password_confirmation]
      if @user.update(user_params)
        # 保存に成功した場合はトップページへリダイレクト
        flash[:success] = "メッセージを編集しました"
        redirect_to user_path(@user)
      else
        # 保存に失敗した場合は編集画面へ戻す
        flash[:danger] = "失敗２"
        render 'edit'
      end
    else
      flash[:danger] = '現在のパスワードor確認用パスワードが間違っています。'
      render 'edit'
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :theme_color)
  end
  
  def set_user
    @user = User.find(params[:id])
    if @user != current_user
      flash[:danger] = "別のユーザーの編集はできません。"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tvs_helper.rb
module TvsHelper
end

app/helpers/tvshows_helper.rb
module TvshowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Heema", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heema</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_tv_form.html.erb
<%= form_for(@tv) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :title, placeholder: "[title]" %>
    <%= f.text_area :introduction, placeholder: "[introduction]" %>
    <%= f.number_field :theme_color, placeholder: "[theme_color]" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_tv_info.html.erb
<!-- link_to gravatar_for(@tv, size: 50), @tv -->
<h1><%= @tv.title %></h1>
<span><%= link_to "made by #{@user.name}", @user %></span>
<span><%= pluralize(@tv.tvshows.count, "tvshow") %></span>

app/views/shared/_tvshow_form.html.erb
<%= form_for(@tvshow) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :video_url, placeholder: "[video_url]" %>
    <%= f.text_area :introduction, placeholder: "[introduction]" %>
    <%= f.hidden_field :tv_id, :value => @tvshow.tv.id %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(@user, size: 50), @user %>
<h1><%= @user.name %></h1>
<span><%= link_to "view my profile", @user %></span>
<span><%= pluralize(@user.tvs.count, "tv") %></span>

app/views/tops/index.html.erb
<h1>Tops#index</h1>
<p>Find me in app/views/tops/index.html.erb</p>

app/views/tvs/_tv.html.erb
<li id="tv-<%= tv.id %>">
  <span class="title"><%= tv.title %></span>
  <span class="introduction"><%= tv.introduction %></span>
  <span class="theme_color"><%= tv.theme_color %></span>
  <span class="more..."><%= link_to "more...", tv %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tv.created_at) %> ago.
    <% if current_user == tv.user %>
      <%= link_to "delete", tv, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/tvs/show.html.erb
@tvshow<%= @tvshow %>
@tvshow.id<%= @tvshow.id %>
@tvshow.video_url<%= @tvshow.video_url %>

<div class="row">
  <aside class="col-md-4">
    <section class="tv_info">
      <%= render 'shared/tv_info' %>
    </section>
    <% if @user==current_user %>
      <section class="tvshow_form">
        <%= render 'shared/tvshow_form' %>
      </section>
    <% end %>
    <% if @tv.tvshows.any? %>
      <h3>Tvshows (<%= @tv.tvshows.count %>)</h3>
      <ol class="tvshows">
        <%= render @tvshows %>
      </ol>
    <% end %>
  </aside>
  <div class="col-md-8">
    <% if @tv.tvshows.any? %>
      <div class="front-tvshow">
        <%# if !(@tvshow.empty?) %>
          <%= render partial: 'tvshows/tvshow', locals: { tvshow: @tvshow } %>
        <%# end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tvshows/_tvshow.html.erb
<li id="tvshow-<%= tvshow.id %>">
    <div class="video-container"><%= raw tvshow.video_url  %></div>
    <span class="introduction"><%= tvshow.introduction %></span>
    <span class="timestamp">
      Posted <%= tvshow.created_at %>
    </span>
    
    <%= form_for tvshow do |f| %>
      <div class="field">
        <%= f.hidden_field :video_url, :value => tvshow.video_url %>
        <%= f.hidden_field :introduction, :value => tvshow.introduction  %>
        <%= f.hidden_field :tv_id, :value => tvshow.tv.id %>
        <%= f.hidden_field :front_tvshow_id, :value => tvshow.id %>
      </div>
      <%= f.submit "再生", class: "btn btn-primary btn-block" %>
    <% end %>
    
    <% if current_user == @tv.user %>
      <%= form_for tvshow, html: {method: "delete"}  do |f| %>
        <%= f.hidden_field :tv_id, :value => @tv.id %>
        <%= f.submit %>
      <% end %>
    <% end %>
</li>

app/views/tvshows/test.html.erb
<%= @tvshow.id %>
<br>
<%= @tv.id %>
<br>
tvshows
<br>
<% @tvshows.each do |tvshow| %>
<%= tvshow.id %>
<br>
<% end %>
    <div class="video-container"><%= raw @video_url %></div>

<li id="tvshow-<%= @tvshow.id %>">
    <span class="introduction"><%= @tvshow.introduction %></span>
    <span class="timestamp">
      Posted <%= @tvshow.created_at %>
    </span>
    
    <%= form_for @tvshow do |f| %>
      <div class="field">
        <%= f.hidden_field :video_url, :value => @tvshow.video_url %>
        <%= f.hidden_field :introduction, :value => @tvshow.introduction  %>
        <%= f.hidden_field :tv_id, :value => @tvshow.tv.id %>
        <%= f.hidden_field :front_tvshow_id, :value => @tvshow.id %>
      </div>
      <%= f.submit "再生", class: "btn btn-primary btn-block" %>
    <% end %>
    
    <% if current_user == @tv.user %>
      <%= form_for @tvshow, html: {method: "delete"}  do |f| %>
        <%= f.hidden_field :tv_id, :value => @tv.id %>
        <%= f.submit %>
      <% end %>
    <% end %>
</li>

app/views/tvshows/update.html.erb
<li id="tvshow-<%= @tvshow.id %>">
    <div class="video-container"><%= raw @tvshow.video_url  %></div>
    <span class="introduction"><%= @tvshow.introduction %></span>
    <span class="timestamp">
      Posted <%= @tvshow.created_at %>
    </span>
    
    <%= form_for @tvshow do |f| %>
      <div class="field">
        <%= f.hidden_field :video_url, :value => @tvshow.video_url %>
        <%= f.hidden_field :introduction, :value => @tvshow.introduction  %>
        <%= f.hidden_field :tv_id, :value => @tvshow.tv.id %>
        <%= f.hidden_field :front_tvshow_id, :value => @tvshow.id %>
      </div>
      <%= f.submit "再生", class: "btn btn-primary btn-block" %>
    <% end %>
    
    <% if current_user == @tv.user %>
      <%= form_for @tvshow, html: {method: "delete"}  do |f| %>
        <%= f.hidden_field :tv_id, :value => @tv.id %>
        <%= f.submit %>
      <% end %>
    <% end %>
</li>

app/views/users/edit.html.erb
<h1><%= @page_title="Setting" %></h1>
<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :introduction %>
  <%= f.text_field :introduction %>
  
  <%= f.label :theme_color %>
  <%= f.text_field :theme_color %>
  
  <%= f.label :password_for_edit, "OLD password" %>
  <%= f.password_field :password_for_edit %>

  <%= f.label :new_password, "NEW password" %>
  <%= f.password_field :new_password %>

  <%= f.label :new_password_confirmation, "Confirmation(NEW password)" %>
  <%= f.password_field :new_password_confirmation %>
  
  <%= f.submit "Done Profile Setting", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <% if @user==current_user %>
      <section class="tv_form">
        <%= render 'shared/tv_form' %>
      </section>
    <% end %>
  </aside>
  <div class="col-md-8">
    <% if @user.tvs.any? %>
      <h3>Tvs (<%= @user.tvs.count %>)</h3>
      <ol class="tvs">
        <%= render @tvs %>
      </ol>
    <% end %>
  </div>
</div>